name: Build PDF
on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set spellcheck as executable
        run: chmod a+x spellcheck
      - name: Print message that we're performing spellcheck
        run: echo "Performing spellcheck..."
      - name: Check spelling of handout.md
        run: |
          MISTAKES="$(./spellcheck handout.md)"
          echo "$MISTAKES"
          [ -z "$MISTAKES" ] || exit 1
          echo "There were no mistakes :)"
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/severinkaderli/pandoc-docker:latest
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Patch Template
        run: cd .latex && git apply ../document_format.patch && cd ..
      - name: Compile MD to PDF
        run: ./.latex/build.sh handout.md
      - uses: actions/upload-artifact@v2
        with:
          name: handout
          path: handout.pdf
